function logPotentialInterferers(outParams,time,interferedId,...
    interfered_x, interfered_y, interferedDirection, interferedSpeed, interferedSensorId, interferedSensor_x, interferedSensor_y, interferedSensorDir, interferedSensorFOV,...
    interferingId, interfering_x, interfering_y, interferingDirection, interferingSpeed, ...
    interferingSensorId, interferingSensor_x, interferingSensor_y, interferingSensorDir, interferingSensorFOV, lengthPathFirst, lengthPathSecond,...
    reflectPointX, reflectPointY)


interferedDirection = atan2(imag(interferedDirection), real(interferedDirection));
interferingDirection = atan2(imag(interferingDirection), real(interferingDirection));


T = table(time,interferedId,...
    interfered_x, interfered_y, interferedDirection, interferedSpeed, interferedSensorId, interferedSensor_x, interferedSensor_y, interferedSensorDir, interferedSensorFOV,...
    interferingId, interfering_x, interfering_y, interferingDirection, interferingSpeed, ...
    interferingSensorId, interferingSensor_x, interferingSensor_y, interferingSensorDir, interferingSensorFOV, lengthPathFirst, lengthPathSecond,...
    reflectPointX, reflectPointY);

tablename = "firstReflectLog";

sqlwrite(outParams.conn,tablename,T);